package com.fnxl.bitflix.feature_discover.domain.model.movie

data class Movie(
    val adult: Boolean = false,
    val backdrop_path: String = "",
    val belongs_to_collection: BelongsToCollection = BelongsToCollection(),
    val budget: Int = Int.MAX_VALUE,
    val credits: Credits = Credits(),
    val external_ids: ExternalIds = ExternalIds(),
    val genres: List<Genre> = emptyList(),
    val homepage: String = "",
    val id: Int = Int.MAX_VALUE,
    val images: Images = Images(),
    val imdb_id: String = "",
    val original_language: String = "",
    val original_title: String = "",
    val overview: String = "",
    val popularity: Double = Double.MIN_VALUE,
    val poster_path: String = "",
    val production_companies: List<ProductionCompany> = emptyList(),
    val production_countries: List<ProductionCountry> = emptyList(),
    val recommendations: Recommendations = Recommendations(),
    val release_date: String = "",
    val recommendation: Releases = Releases(),
    val revenue: Long = Long.MAX_VALUE,
    val runtime: Int = Int.MAX_VALUE,
    val spoken_languages: List<SpokenLanguage> = emptyList(),
    val status: String = "",
    val tagline: String = "",
    val title: String = "",
    val video: Boolean = false,
    val videos: Videos = Videos(),
    val vote_average: Double = Double.MIN_VALUE,
    val vote_count: Int = Int.MAX_VALUE
)