package com.fnxl.bitflix.feature_discover.domain.model.tvshow

data class TVShow(
    val backdrop_path: String = "",
    val content_ratings: ContentRatings = ContentRatings(),
    val created_by: List<CreatedBy> = emptyList(),
    val credits: Credits = Credits(),
    val episode_run_time: List<Int> = emptyList(),
    val external_ids: ExternalIds = ExternalIds(),
    val first_air_date: String = "",
    val genres: List<Genre> = emptyList(),
    val homepage: String= "",
    val id: Int = Int.MIN_VALUE,
    val in_production: Boolean = false,
    val languages: List<String> = emptyList(),
    val last_air_date: String = "",
    val last_episode_to_air: LastEpisodeToAir = LastEpisodeToAir(),
    val name: String = "",
    val networks: List<Network> = emptyList(),
    val next_episode_to_air: LastEpisodeToAir = LastEpisodeToAir(),
    val number_of_episodes: Int = Int.MIN_VALUE,
    val number_of_seasons: Int = Int.MIN_VALUE,
    val origin_country: List<String> = emptyList(),
    val original_language: String = "",
    val original_name: String= "",
    val overview: String= "",
    val popularity: Double = Double.MIN_VALUE,
    val poster_path: String = "",
    val production_companies: List<ProductionCompany> = emptyList(),
    val production_countries: List<ProductionCountry> = emptyList(),
    val recommendations: Recommendations = Recommendations(),
    val seasons: List<Season> = emptyList(),
    val spoken_languages: List<SpokenLanguage> = emptyList(),
    val status: String = "",
    val tagline: String= "",
    val type: String= "",
    val vote_average: Double = Double.MIN_VALUE,
    val vote_count: Int = Int.MIN_VALUE
)